### PR TITLE
Support pixel-based panel constraints

### PR DESCRIPTION
**Pull request by bvaughn**
Relates to issues #46, #47, #51, #78, #114, #128, #141

This PR adds a new prop (`units`) to `PanelGroup`. This prop defaults to "percentage" but can be set to "pixels" for static, pixel based layout constraints.

This can be used to add enable pixel-based min/max and default size values, e.g.:
```tsx
 <PanelGroup direction="horizontal" units="pixels">
   {/* Will be constrained to 100-200 pixels (assuming group is large enough to permit this) */}
   <Panel minSize={100} maxSize={200} />
   <PanelResizeHandle />
   <Panel />
   <PanelResizeHandle />
   <Panel />
 </PanelGroup>
```

Imperative API methods are also able to work with either pixels or percentages now. They default to whatever units the group has been configured to use, but can be overridden with an additional, optional parameter, e.g.
```ts
panelRef.resize(100, "pixels");
panelGroupRef.setLayout([25, 50, 25], "percentages");

// Works for getters too, e.g.
const percentage = panelRef.getSize("percentages");
const pixels = panelRef.getSize("pixels");

const layout = panelGroupRef.getLayout("pixels");
```

See the docs for more: [.../examples/pixel-based-layouts](https://react-resizable-panels-git-panelgroup-layout-val-2424f0-bvaughn.vercel.app/examples/pixel-based-layouts)

### CODE REVIEW

**Comment by lacymorrow** [comment]
Just wanted to mention that it seems like using min/max widths on the `ResizablePrimitive.Panel` allows for constraining the width using pixels.

Granted, I am using the shadcn implementation here: https://ui.shadcn.com/docs/components/resizable

**Comment by lacymorrow** [comment]
> But if you set min-width on Panel then the resizing in the background still works

Can you say more about this? I'm not sure what you mean by "resizing in the background", do you mean programmatically?

**Comment by zac18992** [comment]
@lacymorrow 

For example, first apply the following css or style to a panel:

```
max-width: 500px;
```

Then use the resize handle to expand the width of the panel. Once the panel width reaches 500px, the element will (correctly) not change in size. However, as you drag past 500px, or if you continued to attempt to drag the resize handle to increase the size, the actual width of the panel (within the library) is > 500px.

In summary, if you drag to 650px, the visual element correctly stops expanding at 500px. However, when you drag to decrease the size, you will have a 150px dragging delay before the element starts reducing in width.

@bvaughn This one hurdle could be resolved by having the ability to programatically interrupt resizing a panel. This way, for example we could have something like:

```
shouldResize={({ width, height }) => (width <= 500)}
```

I don't know if this is simple or complex, as this would depend on the implementation within the library.

**Comment by lacymorrow** [comment]
Bravo on illustrating the issue.

For folks in the future: `max-width` can improve the experience, but not solve the problem entirely.

**Comment by bvaughn** [comment]
@zac18992 I've intentionally decided _not_ to support pixel constraints, as mentioned in [the README](https://github.com/bvaughn/react-resizable-panels/?tab=readme-ov-file#can-panel-sizes-be-specified-in-pixels):

> ### Can panel sizes be specified in pixels?
>
> No. Pixel-based constraints [added significant complexity](https://github.com/bvaughn/react-resizable-panels/pull/176) to the initialization and validation logic and so I've decided not to support them. You may be able to implement a version of this yourself following [a pattern like this](https://github.com/bvaughn/react-resizable-panels/issues/46#issuecomment-1368108416) but it is not officially supported by this library.

I haven't thought through the implications of a prop like `shouldResize` but I don't think it would have any use with percentage based constraints, so I would be pretty reluctant to add it.

**Comment by bvaughn** [comment]
You're right to call out the downside of the approach discussed above though! 👍🏼

**Comment by zac18992** [comment]
@piszczu4 @lacymorrow This issue is very important to my use case. I believe I have found my own solution to prevent this, based on the above, but I will try to finalise it before sharing an example, to check if there are any other issues.

@bvaughn I do believe that `shouldResize` (amongst other props) would give greater control, not only solving this issue, but wider use cases that are not tied specifically to percentage or pixel use cases. This prop alone could even prevent resizing based on conditions which don't rely on sizing of panels, such as displayed contents or state.

However, I'm not saying I expect you to implement this. Of course you need to limit the scope so you can be productive. Thanks for replying!

**Comment by bvaughn** [comment]
Thanks for understanding, @zac18992 🙇🏼 

> I will try to finalise it before sharing an example, to check if there are any other issues.

Happy to link to your solution in the FAQ as well!

**Comment by mrmattrc** [comment]
While I understand the desire to keep things simple and easy to work on, removing support for pixels is major pain point for a SAAS project my team is working on. We've resorted to downgrading to v0.0.63 so we can continue using pixel and percentage values. However, we've recently seen some runtime errors (`Cannot read properties of undefined (reading 'collapsedSizePercentage'`), so we are considering our options.

Thankfully, I happened to look through this issue when I did and found @zac18992's solution. I'm hopeful that your solution will work for our use case and maybe even address the runtime errors as well. I'll give it a shot and report back.

**Comment by bvaughn** [comment]
@mrmattrc I'm sorry to hear that your project was negatively impacted by this decision. This is a side project for me though, done pro bono, and I have to keep scope manageable if I want to continue to support the project at all.

If this is a commercial use case, we could always chat about the possibility of me doing some for-hire work.

**Comment by zac18992** [comment]
My use case is always to use responsive layouts (with percentages) but requires min and max values in PX for panels.

[Here](https://codesandbox.io/p/sandbox/panels-with-restricted-min-max-width-y8f9zc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrkutmnl00063b6krikry2ip%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrkutmnl00023b6k7cmznqp6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrkutmnl00033b6kkqszcmh5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrkutmnl00053b6kn3tv7y0a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrkutmnl00023b6k7cmznqp6%2522%253A%257B%2522id%2522%253A%2522clrkutmnl00023b6k7cmznqp6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkutmnl00013b6kozuxz9vw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrkwfa7r00023b6p098t60k7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A55%252C%2522startColumn%2522%253A29%252C%2522endLineNumber%2522%253A55%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrkwfa7r00023b6p098t60k7%2522%257D%252C%2522clrkutmnl00053b6kn3tv7y0a%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkutmnl00043b6kz5lalmiq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrkutmnl00053b6kn3tv7y0a%2522%252C%2522activeTabId%2522%253A%2522clrkutmnl00043b6kz5lalmiq%2522%257D%252C%2522clrkutmnl00033b6kkqszcmh5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrkutmnl00033b6kkqszcmh5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A31.402116402116405%257D) is a contrived example of how I got this with the library as it currently is. It may have some bugs or performance considerations. I haven't explored using the library with purely PX values, but I think the above covers the majority of use cases.

Like I said, this should probably be in the library and would probably be a lot easier to implement, and more performant, if done so. But sounds like @bvaughn needs convincing and then someone needs to create a PR :)

Hope this helps some people!

**Comment by bvaughn** [comment]
Code examples are good, if they've been vetted. I'm willing to link to them in the FAQs if they'll help others (again, only if they've been tested and seem to work well).

But I want to set expectations here regarding feature support for this. I believe that supporting pixel based constraints in this library would be a lot of work (both to implement initially and to maintain over time) and I am **not willing to do it pro bono**. If someone wants to talk about some sort of for-hire arrangement then I'm willing to _consider_ it but I'm not really interested in anything short of that.

I hope you'll all understand that my free time is limited, and it's really important to me to have a good balance between sharing libraries like this and not burning myself out trying to add features for other people (particularly in support of for-profit use cases).

**Comment by zac18992** [comment]
I haven't looked at all the edge cases. But from first glance, I do believe the support would be a lot simpler than it seems. Especially as it can be fudged externally using the existing version. It could probably be added with one prop allowing for control over whether a resize can happen or not. Or probably using a number of other simple approaches as well.

Anyway, I'm currently happy with what I have. If I want to add it to the library then I will just fork it and share, as it sounds like this is not something that will be considered.

Thanks for all your great work on this library. I really appreciate it!

**Comment by bvaughn** [comment]
Having tried to add support already, I think you're under estimating the effort for this. You don't just need to make imperative decisions at the time of a resize / mouse event, you also need to listen for size changes and re-evaluate panel constraints (which can get really complicated).

That being said, fork and share sounds like the way to go.

**Comment by zac18992** [comment]
I can totally see that! Like I said, I haven't looked at all the edge cases, and am not pushing any agenda as I believe I have it working as I desire already :)

**Comment by mrmattrc** [comment]
@bvaughn, re-reading my comment, I feel like I was more harsh than I intended. It's great having a library to handle this functionality, and I really appreciate all your work! We are a small and early-stage start-up though, so we're pretty restricted as far as sponsoring or for-hire work.

It's not perfect, but it looks like [the solution suggested here](https://github.com/bvaughn/react-resizable-panels/pull/176#issuecomment-1898478197) should work pretty well for us! We are running into this minor issue:
> In summary, if you drag to 650px, the visual element correctly stops expanding at 500px. However, when you drag to decrease the size, you will have a 150px dragging delay before the element starts reducing in width.

I agree with @zac18992 that adding something like a `shouldResize` prop seems like it would help. And adding documentation for this use case would also be great!

**Comment by zac18992** [comment]
> @bvaughn, re-reading my comment, I feel like I was more harsh than I intended. It's great having a library to handle this functionality, and I really appreciate all your work! We are a small and early-stage start-up though, so we're pretty restricted as far as sponsoring or for-hire work.
> 
> It's not perfect, but it looks like [the solution suggested here](https://github.com/bvaughn/react-resizable-panels/pull/176#issuecomment-1898478197) should work pretty well for us! We are running into this minor issue:
> 
> > In summary, if you drag to 650px, the visual element correctly stops expanding at 500px. However, when you drag to decrease the size, you will have a 150px dragging delay before the element starts reducing in width.
> 
> I agree with @zac18992 that adding something like a `shouldResize` prop seems like it would help. And adding documentation for this use case would also be great!

Hey @mrmattrc @lacymorrow @piszczu4 check the code sample in my above comment if its of use :)

https://github.com/bvaughn/react-resizable-panels/pull/176#issuecomment-1900823334

**Comment by bvaughn** [comment]
@mrmattrc No worries! :smile: I appreciate your comment though!

I'll let the `shouldResize` idea bounce around my head a bit. I'm concerned that even that could introduce complexity though, when it comes to enforcing group panel constraints. (How should this library handle the case where a panel "refuses" a resize action that's _required_ in order to satisfy another panel's constraints? What if one panel "accepts" a resize, the sibling panel (the one on the other side of the resize bar) doesn't?)

Report back with the approach that's being discussed above. If it works out well for you all then I can add it to the FAQs.

**Comment by rortan134** [comment]
In case anyone is looking for this here's how I managed to do it w/ shadcn. Some glitches still may happen though and it most likely doesn't handle every edge case.

[codesandbox](https://codesandbox.io/p/devbox/react-resizable-panels-z6ns97?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpn68mr200083j6ip4xrmkyf%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpn68mr100033j6ig4uciu1f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpn68mr100053j6iondiss60%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpn68mr200073j6izza4jfuk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B69.43655596843311%252C30.56344403156689%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpn68mr100033j6ig4uciu1f%2522%253A%257B%2522id%2522%253A%2522clpn68mr100033j6ig4uciu1f%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpn68mr200073j6izza4jfuk%2522%253A%257B%2522id%2522%253A%2522clpn68mr200073j6izza4jfuk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpn68mr200063j6ixdn3lmhg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpn68mr200063j6ixdn3lmhg%2522%257D%252C%2522clpn68mr100053j6iondiss60%2522%253A%257B%2522id%2522%253A%2522clpn68mr100053j6iondiss60%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpn68mr100043j6iz3c0loyv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpn68mr100043j6iz3c0loyv%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by DawidWraga** [comment]
The README says that panel sizes cannot be specified in pixels and indeed units="pixels" does not work.

So the fact that this PR was merged, and [these docs](https://react-resizable-panels-git-panelgroup-layout-val-2424f0-bvaughn.vercel.app/examples/pixel-based-layouts) exist is confusing

**Comment by bvaughn** [comment]
@DawidWraga This PR and the CI build for this branch are 9 months old. Pixel-based constraints was something I tried and abandoned when it became clear that there were too many edge cases for me to support them correctly. (This is a side project for me. No one is paying me to build those features.)

**Comment by ev3nst** [comment]
When using only percentage base values it gets too small in smaller screens or too big in bigger screens. Its too unreliable to make a responsive design when things get a bit complex.

**Comment by hipstersmoothie** [comment]
After maintaining my own fork of this library to handle pixel units I created my own

https://react-window-splitter-six.vercel.app/

Some improvements

1. Anything can be either pixel or percentage units
2. No need for an `order` prop
3. "Controlled Collapse" works more like other headless components libraries
4. Built in cookie based persistance
5. Easier access to `ref` and imperative `handle`

(Thanks @bvaughn for the amazing library and API <3)

**Comment by bvaughn** [comment]
Hey @hipstersmoothie! That's awesome! Thanks for sharing the update 😃 

I wonder if it would be possible to backport any of the non-pixel-based improvements you mentioned (like the order prop or the controlled collapse bits). I'd be interested in chatting if you think it would be doable (but also, totally understand if it's not something you'd be interested in)

Either way, nice work!

**Comment by Janpot** [comment]
Ah interesting, I also did a `react-resizable-panels` lookalike because I wanted more units and better SSR support. It's not a fork, but heavily inspired. You can find it here if anyone is interested:

https://split-ui-docs.vercel.app/react

Main differences are:
* it allows any CSS length, + calculations, and even variables
* it does persistence in localstorage and does SSR without a FOUC, and without needing cookies. Meaning you can use this in statically exported pages.
* it doesn't support collapsible panels, deliberately for now
* resizing works over iframes
* it's about half the bundle size atm

**Pull request merged**
