### PR TITLE
call onFocus/onBlur

### PR DESCRIPTION
**Pull request by hipstersmoothie**
Noticed the component accepted the props but didn't use them

### CODE REVIEW

**Comment by bvaughn** [comment]
Hmm seems like this change broke one of the `PanelResizeHandle` unit tests. Not sure why yet.

**Comment by bvaughn** [comment]
Version 2.0.20 just deployed with this change.

**Comment by hipstersmoothie** [comment]
Thanks!

**Comment by bvaughn** [comment]
Yup!

**Pull request merged**
