### PR TITLE
VS code behaviour on open as well

### PR DESCRIPTION
**Pull request by kristian240**

### CODE REVIEW

**Comment by kristian240** [comment]
@bvaughn What do you say? VSCode works like this and it would be much better UX.

**Comment by bvaughn** [comment]
Once #182, I'll revisit (if this PR is still even needed) but I don't have the bandwidth to merge and rebase anything in the meanwhile.

**Comment by bvaughn** [comment]
#182 has shipped! Can you rebase this and add/update tests?

**Comment by bvaughn** [comment]
I think I might make this change myself as part of addressing #210

**Comment by bvaughn** [comment]
Going to close this since it's against the old implementation.

**Pull request closed without merging**
